<Project Sdk="Microsoft.NET.Sdk">
	<Import Project="..\tModLoader.targets" />

  <PropertyGroup>
    <AssemblyName>SpikysLib</AssemblyName>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <!-- <PublicizerRuntimeStrategies>Unsafe</PublicizerRuntimeStrategies> -->
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Krafs.Publicizer" Version="2.3.0">
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      <PrivateAssets>all</PrivateAssets>
    </PackageReference>
    <Publicize Include="tModLoader" IncludeCompilerGeneratedMembers="false" IncludeVirtualMembers="false" />
  	<Publicize Include="tModLoader:Terraria.ModLoader.Config.UI.ConfigElement.DrawSelf" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="../ModAssemblies/MagicStorage_v0.7.0.1.dll" />
  </ItemGroup>
</Project>